### ISSUE TITLE
Διόρθωση σύνταξης στις μεταφράσεις του bigbluebuttonbn.php 

### ISSUE THREAD

**Issue by pkst-ellak** [eellak/lms-translations#1]
Πολλές από τις μεταφράσεις στο bigbluebuttonbn.php  χρειάζονται review γιατί περιέχουν σημαντικά συντακτικά λάθη με αποτέλεσμα να είναι σχεδόν ακατανόητες.
π.χ "Περιμένετε για την αξία μεσολαβητή εξ ορισμού μπορούν να επεξεργαστούν" στο bigbluebuttonbn.php (χρειάζεται όλο αυτό το αρχείο έλεγχο- εχει πάρα πολλά τέτοια σφάλματα).
 Αντίθετα το bbbResources.properties, το recordingsbn.php και το moodlemobileapp.php εχει ελάχιστα  τέτοια σφάλματα (π.χ "Cache χρόνος λήξης" )

**Comment by dalexo** [comment]
Fix in progress.

**Comment by dalexo** [comment]
fix completed
